version: '3.8'

services:
  db:
    build: .
    container_name: animalsim
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=animalsim
    ports:
      - "25060:5432"
    command: >
      postgres -c shared_preload_libraries=pg_cron
               -c cron.database_name=animalsim
